/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'blank',
    path: '/blank',
    component: 'layout.base$view.blank',
    meta: {
      title: 'blank',
      i18nKey: 'route.blank',
      icon: 'solar:widget-3-linear'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'inbox',
    path: '/inbox',
    component: 'layout.base$view.inbox',
    meta: {
      title: 'inbox',
      i18nKey: 'route.inbox',
      icon: 'solar:inbox-linear'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'marketplace',
    path: '/marketplace',
    component: 'layout.base$view.marketplace',
    meta: {
      title: 'marketplace',
      i18nKey: 'route.marketplace',
      icon: 'solar:shop-linear'
    }
  },
  {
    name: 'routing',
    path: '/routing',
    component: 'layout.base$view.routing',
    meta: {
      title: 'routing',
      i18nKey: 'route.routing',
      icon: 'solar:route-linear'
    }
  }
];
